FROM node:16

# package update & install
RUN apt update && apt upgrade -y && \
    apt install -y curl unzip wget -y

# Execute command after mounting a volume
CMD bash -c "npm install"
CMD bash -c "npm run start --host 0.0.0.0"
