version: "3.8"

services:
  web:
    build: nginx
    restart: always
    ports:
      - "80:80"
    working_dir: /etc/nginx

  database:
    image: mysql:8
    hostname: database
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - database-volume:/var/lib/mysql

  frontend:
    build: ${BUILD_FRONT}
    hostname: frontend
    working_dir: ${DIR_APP}
    volumes:
      - frontend-volume:${DIR_APP}
      - ${DIR_FRONT}:${DIR_APP}

  backend:
    build: ${BUILD_BACK}
    hostname: backend
    working_dir: ${DIR_APP}
    volumes:
      - backend-volume:${DIR_APP}
      - ${DIR_BACK}:${DIR_APP}

volumes:
  frontend-volume:
  backend-volume:
  database-volume:
