version: "3.8"

services:
  frontend:
    build: docker-node
    ports:
      - "3000:3000"
    working_dir: ${WORK_DIR}
    volumes:
      - node-volume:${WORK_DIR}
      - ${FRONTEND_DIR}:${WORK_DIR}

  backend:
    build: docker-laravel
    ports:
      - "8000:8000"
    working_dir: ${WORK_DIR}
    volumes:
      - laravel-volume:${WORK_DIR}
      - ${BACKEND_DIR}:${WORK_DIR}

volumes:
  node-volume:
  laravel-volume:
