version: "3.8"

services:
  database:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
      MYSQL_USER: kimchanhyung98
      MYSQL_PASSWORD: secret
    ports: 
      - 3306:3306

  web:
    container_name: nginx
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 80:80
      #- 443:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /var/www/project
    depends_on:
      - database
