FROM node:16.14

# package update & install
RUN apt update && apt upgrade -y && \
    apt install -y curl unzip wget -y
RUN npm install -g npm@8.5.4

# Execute command after mounting a volume
CMD bash -c "npm i --force && npm run start:dev"
